### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by lakshman-1396** [conda-forge/implicit-feedstock#21]
Issue:
I am trying to manually install impliit-feedstock. when i try to build locally its says it is currently supported for Linux. is this not supported for windows?
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by benfred** [comment]
There are Windows/OSX/Linux binaries built here: https://anaconda.org/conda-forge/implicit/files

To install going ```conda install implicit -c condforge``` should work
