### ISSUE TITLE
Docker image building error?

### ISSUE THREAD

**Issue by hanzigs** [conda-forge/implicit-feedstock#23]
Issue: ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'D:\\bld\\implicit_1591810443891\\work'

Building a Docker image with below python image, using tensorflow 2.2.0
```
python:3.7.4-windowsservercore-1809
```
The python file has fuzzywuzzy module, so I was getting following error, 
```
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for python-Levenshtein
```
To fix this, I followed https://github.com/benfred/implicit/issues/76

so installed 
conda config --add channels conda-forge
conda install implicit

so, that error gone, but now I am getting this error
```
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'D:\\bld\\implicit_1591810443891\\work'
```
The python file working in local and also in a new py env without any issues, while building the docker images for that giving issues.

May I know how to fix this, Thanks

**Comment by benfred** [comment]
Looks like you were having some issues installing python-levenstein or fuzzywuzzy?    I'm not sure what the conda error with implicit was about, but you shouldn't need to install this package to get  python-levenstein or fuzzywuzzy
